### ISSUE TITLE
Domain Services should be DI'd into the Spring's IOC

### ISSUE THREAD

**Issue by berkayerten** [beergode/tech-thrive-catalyst#2]
Beans under domain module should be registered to Spring's (IOC) Container. 

This can be achiieved by annotation the services under domain module as `@DomainComponent` or similar. Then the annotated classes should be collected to be injected into the IOC.

**Comment by mehmetugurakpinar** [comment]
I am assigning this tast to myself if it is okay for you as well.  Please feel free to contact me if you have any other ideas or suggestions regarding it.

**Comment by berkayerten** [comment]
Thank you @mehmetugurakpinar, thank you!

**Comment by berkayerten** [comment]
Is it easy to follow hexagonal-demo repository to implement a similar approach here?

**Comment by mehmetugurakpinar** [comment]
I think yes. Not looking so hard. I'll keep you informed soon.

**Comment by berkayerten** [comment]
@gokhandegerli This issue is resolved. You should be unblocked
