### ISSUE TITLE
A survey is able to create multiple questions

### ISSUE THREAD

**Issue by berkayerten** [beergode/tech-thrive-catalyst#22]
Users want to ask multiple questions in a single survey. 

- [ ] There can be multiple questions in a survey which are separated by steppers
- [ ] Each question can have their  own answers

**Comment by berkayerten** [comment]
@gokhandegerli can this ticket be closed in your opinion?

**Comment by gokhandegerli** [comment]
@berkayerten It can be closed, the feature is working proper, and I am closing it. Thanks, well done!
