### ISSUE TITLE
Re-iterate survey with short answers

### ISSUE THREAD

**Issue by berkayerten** [beergode/tech-thrive-catalyst#23]
Authors want to restart to survey together with the given short answers for a second round.

**AC**
- [x] Author can edit the short answers before restarting the survey
- [x] Author ~~cannot~~ can edit existing answers
- [x] Authors can delete given short answers
- [x] Reset the existing vote counts
- [x] Reset custom and non-custom answers
- [x] The new survey (restarted one) does not allow short answers, anymore
- [x] Third iteration is not possible
- [x] Surveys which do not initially allow short answers cannot be reiterated (`customEnabled: false`) 

**Additional Information:**
- Can be solved by deleting the existing survey and recreating from scratch

**Comment by gokhandegerli** [comment]
@berkayerten and @mehmetugurakpinar, it is ready to test

**Comment by catchsoft** [comment]
Looks good! Closing this one

**Comment by berkayerten** [comment]
Thank you @gokhandegerli. Really good job! Closing this one.
