### ISSUE TITLE
Donut Chart Does Not Consider Short Answers

### ISSUE THREAD

**Issue by berkayerten** [beergode/tech-thrive-catalyst#24]
Add Total Count of Short Answers into a Single Category "Other" in Donut Chart

**Comment by gokhandegerli** [comment]
@berkayerten I have pushed with "DCM issue 24, #patch" commit on FE repo, please review and close issue if everything looks fine, otherwise advise.

**Comment by berkayerten** [comment]
The donut part looks as expected. Great job! Closing this one.

But I found another related one (https://github.com/beergode/tech-thrive-catalyst/issues/25) while testing this
