### ISSUE TITLE
Submitted Short Answers are Immediately Visible

### ISSUE THREAD

**Issue by berkayerten** [beergode/tech-thrive-catalyst#25]
**Steps to reproduce:**
- Create a survey and allow short answers
- Go to the survey
- Give short answers with users.

**Actual Result:**
- Short answers are immediately visible among listed options as soon as submitted

**Expected Result:
- Short answers are hidden until the author re-iterates survey

**Comment by gokhandegerli** [comment]
Answers with field of voteCount is null are hidden now, @berkayerten. Updates are in the "DCM issue 25, #patch" commit.

**Comment by berkayerten** [comment]
I tested. Works as expected ✅ 

Thank you @gokhandegerli 

Closing now!
