### ISSUE TITLE
Find Data Mocker For Unit Tests

### ISSUE THREAD

**Issue by berkayerten** [beergode/tech-thrive-catalyst#26]
There are some open source data mocking tools out there. Which can simplify the data generation which is used during the tests.

Some options are below. Investigate and implement an example from one of them

1. [Podam](https://github.com/mtedone/podam) (MIT License)
2. [Instancio](https://github.com/instancio/instancio) (Apache License)
3. [Java faker](https://github.com/DiUS/java-faker) (Apache License)

**Comment by berkayerten** [comment]
Decided to go with Instancio, as it offers the most extensive usage

**Comment by berkayerten** [comment]
@gokhandegerli this is in place now. You can have a look at the example for SurveyCreate use case and then close 🙏

**Comment by gokhandegerli** [comment]
Thank you @berkayerten, it looks fine! Closing this one.

**Comment by gokhandegerli** [comment]
Thank you @berkayerten, it looks fine! Closing this one.
