### ISSUE TITLE
A new survey can be created by an author

### ISSUE THREAD

**Issue by berkayerten** [beergode/tech-thrive-catalyst#3]
**Description:**

Users would like to create surveys for a targeted group of people. They aim to give everyone in the group a chance to provide their opinion so that they can make/ agree on a decision together.

**A.C.**

- [x] User can provide questions,
  -  [x] Choice Question with defined answers
  -  [x] ~#20~ Extracted to a separate issue -> #21 
- [x] User can choose predefined countdown time of 15, 30, 60, or 120 seconds
- [x] User can add a note
- [x] ~User can select a passcode to restrict access to the question~ Removed since private surveys do not require a passcode because they are already shared via a private link

**Comment by gokhandegerli** [comment]
Has project structure setup been resolved? I still can not build the project and getting following error: "Cause: error=2, No such file or directory", is it related with me? or a general issue?

**Comment by gokhandegerli** [comment]
I am in charge of this issue which deals with creating a new decision use case, not the "join" feature
