### ISSUE TITLE
Attach a ReadMe

### ISSUE THREAD

**Issue by berkayerten** [beergode/tech-thrive-catalyst#4]
- Mention tech stack used
- Mention architecture used
- Describe purpose shortly
- Describe project(s)
- Include how to setup locally
- Include docker setup

**Comment by mehmetugurakpinar** [comment]
I've added a README to the project, but I didn't include any information about Docker. Could you take a look and let me know if you see any gaps or areas that need improvement? @berkayerten @gokhandegerli

**Comment by berkayerten** [comment]
Hi @mehmetugurakpinar - it's great you started this ❤️ . Could you please also mention, 

- Features: Shall we mention that this tool can also be used for public surveying besides private decision making?
- tech stack: We can also mention Java is of **version 21**,  and Spring 3.2.X, MongoDB.
- Architecture: DDD/ Hexagonal
- To run project with Docker you can add:
  - `cd decision-maker/infra`
  - `docker compose up -d`

**Comment by mehmetugurakpinar** [comment]
Done but open to improve.
