### ISSUE TITLE
Enhance Joining to an Existing Survey

### ISSUE THREAD

**Issue by berkayerten** [beergode/tech-thrive-catalyst#6]
Users should be able to join the already existing collaborations and provide their opinion on the decision to be made.

**A.C**
-

- [x] Users can provide the **link** to join the existing survey
- [x] Users can provide the **handling key** to join the existing survey
- [x] Users can see the content of the survey
- [x] If there is a limitation like, max user count or pass key while joining the survey, they should also be validated and the respective error should be returned

**Comment by mehmetugurakpinar** [comment]
I've made the necessary changes. Can you check it out? @berkayerten @gokhandegerli

**Comment by berkayerten** [comment]
Lgtm
